[tool.poetry]
name = "bookit - backend"
version = "0.1.0"
description = ""
authors = ["codebyaadi <adityastar57@gmail.com>"]
license = ""
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
